### ISSUE TITLE
error on load up 1.14.1 fabric   Exception in thread "Client thread" java.lang.RuntimeException

### ISSUE THREAD

**Issue by SDUBZ** [CottonMC/cotton#22]
fabric: 1.14.1
cotton: cotton-0.6.7+1.14.1-SNAPSHOT

 Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:172)
 at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
 at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
 Caused by: java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
 ... 2 more
 Caused by: java.lang.NoClassDefFoundError: net/minecraft/item/ItemStack
 at io.github.cottonmc.cotton.config.ConfigManager.getBaseJankson(ConfigManager.java:22)
 at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:52)
 at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:48)
 at io.github.cottonmc.resources.CottonResources.<clinit>(CottonResources.java:14)
 at net.minecraft.class_3864.handler$mixinDefaultOres$zmo000(class_3864.java:517)
 at net.minecraft.class_3864.method_17006(class_3864.java)
 at net.minecraft.class_2075.<init>(class_2075.java:43)
 at net.minecraft.class_1972.<clinit>(class_1972.java:9)
 at net.minecraft.class_2378.method_10242(class_2378.java:86)
 at net.minecraft.class_2378$$Lambda$97/1013620810.get(Unknown Source)
 at net.minecraft.class_2378.method_10238(class_2378.java:117)
 at net.minecraft.class_2378$$Lambda$122/1996556848.accept(Unknown Source)
 at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
 at net.minecraft.class_2378.<clinit>(class_2378.java:116)
 at net.minecraft.class_2966.method_12851(class_2966.java:38)
 at net.minecraft.class_310.<init>(class_310.java:384)
 at net.minecraft.client.main.Main.main(Main.java:154)
 ... 7 more
 Caused by: java.lang.ClassNotFoundException: net.minecraft.item.ItemStack
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 24 more

log: 
[latest.log](https://github.com/CottonMC/cotton/files/3190370/latest.log)

**Comment by Boundarybreaker** [comment]
Oh, boy. Looks like a messed up build. See if [this](http://server.bbkr.space:8081/artifactory/libs-snapshot/io/github/cottonmc/cotton/0.6.7+1.14.1-SNAPSHOT/cotton-0.6.7+1.14.1-20190517.015742-2.jar) works.

**Comment by SDUBZ** [comment]
yes that build works now a another mod is crashing xD
you might wanan push that one to curseforge for others :)

**Comment by SDUBZ** [comment]
quick question will it be possible to run 1.14 and 1.14.1 mods along side each other no matter loader versions

**Comment by Boundarybreaker** [comment]
It depends. The main worry is if mods nest both Fabric API 0.2.7 and Fabric API 0.3.0. 0.3.0 is the new version for 1.14.1+, and will crash if it comes into contact with 0.2.7. The files in each version are effectively the same, though, so if you only have one version in your pack, you'll be fine.

**Comment by SDUBZ** [comment]
thats becoming a problem quick because some devs are using 0.2.7 and some are using 0.3.0

**Comment by Boundarybreaker** [comment]
Yeah, there's basically a hard line between the two versions. Luckily, it's a line that's only one line of code away from being fixed for 99% of mods, so mods will be coming to 1.14.1 quickly.
