### ISSUE TITLE
RecipeUtil.removeRecipeFor prevents creating world with TechReborn

### ISSUE THREAD

**Issue by JFronny** [CottonMC/cotton#48]
**Describe the bug**
My mod recently began having compatibility problems with TechReborn. I decided to try to find out where the issue lies. Apparently a mod only containing the line `RecipeUtil.removeRecipeFor(new ItemStack(Items.DIAMOND_AXE));` inside `onInitialize` and a copy of cotton-datapack and dependencies as jij mods:
```
modImplementation "io.github.cottonmc.cotton:cotton-datapack:1.0.5"
include "io.github.cottonmc.cotton:cotton-datapack:1.0.5"
include "io.github.cottonmc:Jankson-Fabric:3.0.0+j1.2.0"
include "io.github.cottonmc.cotton:cotton-config:1.0.0-rc.7"
include "io.github.cottonmc.cotton:cotton-logging:1.0.0-rc.4"
```
causes minecraft to throw an exception when creating a new world. The game doesn't crash but displays:
`Failed to load datapacks, can't proceed with server load` (console)

**To Reproduce**
1. Create the mod described above (or use my artifact: [here](https://drive.google.com/file/d/13i6WSLZiy7ydnPfJHM32X8NH9nCtCzKL/view?usp=sharing))
2. Create a new minecraft instance (I used MultiMC for convenience) with the mod, fabric api 0.14.1+build.272-1.16 and TechReborn 1.16-3.4.3+build.72 (I have also tested other versions, TechReborn stable crashes too)
3. Try to create a new world

**Expected behavior**
I should be able to create a new world

**Screenshots**
[here](https://drive.google.com/file/d/1F7ADiDnZmaWZmRWEKCAMetQRSHF62l-3/view?usp=sharing)

**Version of the (please complete the following information):**
 - cotton-datapack:1.0.5
 - Jankson-Fabric:3.0.0+j1.2.0
 - cotton-config:1.0.0-rc.7
 - cotton-logging:1.0.0-rc.4
 - TechReborn-1.16-3.4.3+build.72
 - fabric-api-0.14.1+build.372-1.16
 - Minecraft 1.16.1

**Comment by LemmaEOF** [comment]
oh dear. This  Does the console have any stacktrace?

**Comment by JFronny** [comment]
```
[11:35:24] [main/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_252]
	at net.minecraft.class_310.method_29604(class_310.java:1905) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1754) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1702) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:287) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:226) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:33) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:149) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1044) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.1-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.UnsupportedOperationException
	at reborncore.common.crafting.RebornRecipe.method_8110(RebornRecipe.java:228) ~[8a41f406-9441-470e-9e4e-8c0761216e09.jar:?]
	at io.github.cottonmc.cotton.datapack.recipe.RecipeUtil$ProductRemovalPredicate.test(RecipeUtil.java:66) ~[63ab9545-3366-4f57-9958-983e089c39a4.jar:?]
	at io.github.cottonmc.cotton.datapack.recipe.RecipeUtil$ProductRemovalPredicate.test(RecipeUtil.java:58) ~[63ab9545-3366-4f57-9958-983e089c39a4.jar:?]
	at net.minecraft.class_1863.redirect$zed000$onPutRecipe(class_1863.java:1047) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_29604(class_310.java:1904) ~[intermediary-minecraft-1.16.1-client.jar:?]
	... 36 more
```

**Comment by LemmaEOF** [comment]
uuuuuggggghhhhh not this again, I had to fix this in LibCD and I guess I'll have to fix it here too
